#include <stdio.h>
int Counter;
RecordInst(){Counter++;}
Init(){Counter = 0;}
Report(){printf("No. of instructions are %d\n", Counter);}
/* FileAst "trivia.adap" Begin */
int main(int p0, char** p1) ;

int main(int argc, char** argv) {
      int temp_21;
      int temp_20;
      int temp_19;
      int temp_18;
      int temp_17;
      int temp_16;
      int temp_15;
      int temp_14;
      int temp_13;
      int temp_12;
      int temp_11;
      int temp_10;
      int temp_9;
      int temp_8;
      int temp_7;
      int temp_6;
      int temp_5;
      int temp_4;
      int temp_3;
      int temp_2;
      int temp_1;
      int temp_0;
      int b;
      int s;
      int a;
      int c;
      Init();
      RecordInst();
      printf("Please input an integer number: ");
      RecordInst();
      scanf("%d", (&a));
      RecordInst();
      b = 50;
      RecordInst();
      c = 500;
      RecordInst();
      s = 0;
      RecordInst();
      temp_0 = (c / c);
      RecordInst();
      s = (s / temp_0);
      RecordInst();
      temp_1 = (c + c);
      RecordInst();
      s = (s + temp_1);
      RecordInst();
      temp_2 = (c / a);
      RecordInst();
      s = (s / temp_2);
      RecordInst();
      c = (b + c);
      RecordInst();
      temp_3 = (b + a);
      RecordInst();
      s = (s + temp_3);
      RecordInst();
      temp_4 = (b + a);
      RecordInst();
      s = (s + temp_4);
      RecordInst();
      temp_5 = (b + c);
      RecordInst();
      s = (s + temp_5);
      RecordInst();
      temp_6 = (a + b);
      RecordInst();
      s = (s + temp_6);
      RecordInst();
      temp_7 = (a / a);
      RecordInst();
      s = (s / temp_7);
      RecordInst();
      c = (b / a);
      RecordInst();
      temp_8 = (b / a);
      RecordInst();
      s = (s / temp_8);
      RecordInst();
      temp_9 = (c + b);
      RecordInst();
      s = (s + temp_9);
      RecordInst();
      temp_10 = (a + b);
      RecordInst();
      s = (s + temp_10);
      RecordInst();
      temp_11 = (c + a);
      RecordInst();
      s = (s + temp_11);
      RecordInst();
      temp_12 = (c + c);
      RecordInst();
      s = (s + temp_12);
      RecordInst();
      temp_13 = (c + b);
      RecordInst();
      s = (s + temp_13);
      RecordInst();
      c = (b + a);
      RecordInst();
      temp_14 = (c / b);
      RecordInst();
      s = (s / temp_14);
      RecordInst();
      b = (c + a);
      RecordInst();
      temp_15 = (b / a);
      RecordInst();
      s = (s / temp_15);
      RecordInst();
      temp_16 = (a + b);
      RecordInst();
      s = (s + temp_16);
      RecordInst();
      temp_17 = (c + b);
      RecordInst();
      s = (s + temp_17);
      RecordInst();
      temp_18 = (c + a);
      RecordInst();
      s = (s + temp_18);
      RecordInst();
      c = (a + a);
      RecordInst();
      temp_19 = (a + c);
      RecordInst();
      s = (s + temp_19);
      RecordInst();
      c = (b + a);
      RecordInst();
      temp_20 = (a + a);
      RecordInst();
      s = (s + temp_20);
      RecordInst();
      c = (b / a);
      RecordInst();
      c = (b / c);
      RecordInst();
      a = (a / c);
      RecordInst();
      temp_21 = (b + a);
      RecordInst();
      s = (s + temp_21);
      RecordInst();
      printf("Final Result: s = %d\n", s);
      Report();
      return 0;
   L1:;
      Report();
}
/* FileAst "trivia.adap" End */
