/* ProgAst "sort.adap" Begin */
	/* FileAst "sort.adap" Begin */
int counter;
void init() ;

void init() {
      counter = 0;
}
void recordInst() ;

void recordInst() {
      counter = (counter + 1);
}
void report() ;

void report() {
      printf("instruction %d", counter);
}
int array_1[16];
int array_2[16];
int array_3[16];
int array_4[16];
void populate_arrays() ;

void populate_arrays() {
      
      recordInst();
      array_1[0]  = 0;
      recordInst();
      array_2[0]  = 15;
      recordInst();
      array_3[0]  = 5;
      recordInst();
      array_4[0]  = 13;
      recordInst();
      array_1[1]  = 1;
      recordInst();
      array_2[1]  = 14;
      recordInst();
      array_3[1]  = 5;
      recordInst();
      array_4[1]  = 9;
      recordInst();
      array_1[2]  = 2;
      recordInst();
      array_2[2]  = 13;
      recordInst();
      array_3[2]  = 5;
      recordInst();
      array_4[2]  = 12;
      recordInst();
      array_1[3]  = 3;
      recordInst();
      array_2[3]  = 12;
      recordInst();
      array_3[3]  = 5;
      recordInst();
      array_4[3]  = 1;
      recordInst();
      array_1[4]  = 4;
      recordInst();
      array_2[4]  = 11;
      recordInst();
      array_3[4]  = 5;
      recordInst();
      array_4[4]  = 0;
      recordInst();
      array_1[5]  = 5;
      recordInst();
      array_2[5]  = 10;
      recordInst();
      array_3[5]  = 5;
      recordInst();
      array_4[5]  = 14;
      recordInst();
      array_1[6]  = 6;
      recordInst();
      array_2[6]  = 9;
      recordInst();
      array_3[6]  = 5;
      recordInst();
      array_4[6]  = 3;
      recordInst();
      array_1[7]  = 7;
      recordInst();
      array_2[7]  = 8;
      recordInst();
      array_3[7]  = 5;
      recordInst();
      array_4[7]  = 2;
      recordInst();
      array_1[8]  = 8;
      recordInst();
      array_2[8]  = 7;
      recordInst();
      array_3[8]  = 5;
      recordInst();
      array_4[8]  = 11;
      recordInst();
      array_1[9]  = 9;
      recordInst();
      array_2[9]  = 6;
      recordInst();
      array_3[9]  = 5;
      recordInst();
      array_4[9]  = 8;
      recordInst();
      array_1[10]  = 10;
      recordInst();
      array_2[10]  = 5;
      recordInst();
      array_3[10]  = 5;
      recordInst();
      array_4[10]  = 6;
      recordInst();
      array_1[11]  = 11;
      recordInst();
      array_2[11]  = 4;
      recordInst();
      array_3[11]  = 5;
      recordInst();
      array_4[11]  = 4;
      recordInst();
      array_1[12]  = 12;
      recordInst();
      array_2[12]  = 3;
      recordInst();
      array_3[12]  = 5;
      recordInst();
      array_4[12]  = 5;
      recordInst();
      array_1[13]  = 13;
      recordInst();
      array_2[13]  = 2;
      recordInst();
      array_3[13]  = 5;
      recordInst();
      array_4[13]  = 10;
      recordInst();
      array_1[14]  = 14;
      recordInst();
      array_2[14]  = 1;
      recordInst();
      array_3[14]  = 5;
      recordInst();
      array_4[14]  = 7;
      recordInst();
      array_1[15]  = 15;
      recordInst();
      array_2[15]  = 0;
      recordInst();
      array_3[15]  = 5;
      recordInst();
      array_4[15]  = 15;
   L1:;
}
void print_arrays() ;

void print_arrays() {
      {
      int idx;
      int bound;
      recordInst();
      bound = 16;
      recordInst();
      printf("Array_1:\n");
      recordInst();
      idx = 0;
      recordInst();
      goto L5;
   L4:;
      {
      int temp_0;
      recordInst();
      temp_0 = (1 * idx);
      int temp_1;
      recordInst();
      temp_1 = array_1[temp_0] ;
      recordInst();
      printf("%d\n", temp_1);
      recordInst();
      idx = (idx + 1);
      }
   L5:;
      recordInst();
      if ((idx < bound)) goto L4;
      recordInst();
      printf("\nArray_2:\n");
      recordInst();
      idx = 0;
      recordInst();
      goto L10;
   L9:;
      {
      int temp_2;
      recordInst();
      temp_2 = (1 * idx);
      int temp_3;
      recordInst();
      temp_3 = array_2[temp_2] ;
      recordInst();
      printf("%d\n", temp_3);
      recordInst();
      idx = (idx + 1);
      }
   L10:;
      recordInst();
      if ((idx < bound)) goto L9;
      recordInst();
      printf("\nArray_3:\n");
      recordInst();
      idx = 0;
      recordInst();
      goto L14;
   L13:;
      {
      int temp_4;
      recordInst();
      temp_4 = (1 * idx);
      int temp_5;
      recordInst();
      temp_5 = array_3[temp_4] ;
      recordInst();
      printf("%d\n", temp_5);
      recordInst();
      idx = (idx + 1);
      }
   L14:;
      recordInst();
      if ((idx < bound)) goto L13;
      recordInst();
      printf("\nArray_4:\n");
      recordInst();
      idx = 0;
      recordInst();
      goto L18;
   L17:;
      {
      int temp_6;
      recordInst();
      temp_6 = (1 * idx);
      int temp_7;
      recordInst();
      temp_7 = array_4[temp_6] ;
      recordInst();
      printf("%d\n", temp_7);
      recordInst();
      idx = (idx + 1);
      }
   L18:;
      recordInst();
      if ((idx < bound)) goto L17;
      recordInst();
      printf("\n");
      }
   L2:;
}
int main() ;

int main() {
      init();
      {
      int idx;
      int bound;
      int temp;
      recordInst();
      bound = 16;
      recordInst();
      populate_arrays();
      recordInst();
      print_arrays();
      recordInst();
      bound = 16;
      recordInst();
      idx = 0;
      recordInst();
      goto L23;
   L22:;
      {
      int temp_8;
      recordInst();
      temp_8 = (1 * idx);
      int temp_9;
      recordInst();
      temp_9 = array_1[temp_8] ;
      int temp_10;
      recordInst();
      temp_10 = (1 * idx);
      int temp_11;
      recordInst();
      temp_11 = (temp_10 + 1);
      int temp_12;
      recordInst();
      temp_12 = array_1[temp_11] ;
      recordInst();
      if ((temp_9 <= temp_12)) goto L25;
      {
      int temp_13;
      recordInst();
      temp_13 = (1 * idx);
      recordInst();
      temp = array_1[temp_13] ;
      int temp_14;
      recordInst();
      temp_14 = (1 * idx);
      int temp_15;
      recordInst();
      temp_15 = (1 * idx);
      int temp_16;
      recordInst();
      temp_16 = (temp_15 + 1);
      recordInst();
      array_1[temp_14]  = array_1[temp_16] ;
      int temp_17;
      recordInst();
      temp_17 = (1 * idx);
      int temp_18;
      recordInst();
      temp_18 = (temp_17 + 1);
      recordInst();
      array_1[temp_18]  = temp;
      recordInst();
      idx = 0;
      recordInst();
      goto L23;
      }
   L25:;
      recordInst();
      idx = (idx + 1);
      }
   L23:;
      int temp_19;
      recordInst();
      temp_19 = (bound - 1);
      recordInst();
      if ((idx < temp_19)) goto L22;
      recordInst();
      idx = 0;
      recordInst();
      goto L28;
   L27:;
      {
      int temp_20;
      recordInst();
      temp_20 = (1 * idx);
      int temp_21;
      recordInst();
      temp_21 = array_2[temp_20] ;
      int temp_22;
      recordInst();
      temp_22 = (1 * idx);
      int temp_23;
      recordInst();
      temp_23 = (temp_22 + 1);
      int temp_24;
      recordInst();
      temp_24 = array_2[temp_23] ;
      recordInst();
      if ((temp_21 <= temp_24)) goto L30;
      {
      int temp_25;
      recordInst();
      temp_25 = (1 * idx);
      recordInst();
      temp = array_2[temp_25] ;
      int temp_26;
      recordInst();
      temp_26 = (1 * idx);
      int temp_27;
      recordInst();
      temp_27 = (1 * idx);
      int temp_28;
      recordInst();
      temp_28 = (temp_27 + 1);
      recordInst();
      array_2[temp_26]  = array_2[temp_28] ;
      int temp_29;
      recordInst();
      temp_29 = (1 * idx);
      int temp_30;
      recordInst();
      temp_30 = (temp_29 + 1);
      recordInst();
      array_2[temp_30]  = temp;
      recordInst();
      idx = 0;
      recordInst();
      goto L28;
      }
   L30:;
      recordInst();
      idx = (idx + 1);
      }
   L28:;
      int temp_31;
      recordInst();
      temp_31 = (bound - 1);
      recordInst();
      if ((idx < temp_31)) goto L27;
      recordInst();
      idx = 0;
      recordInst();
      goto L33;
   L32:;
      {
      int temp_32;
      recordInst();
      temp_32 = (1 * idx);
      int temp_33;
      recordInst();
      temp_33 = array_3[temp_32] ;
      int temp_34;
      recordInst();
      temp_34 = (1 * idx);
      int temp_35;
      recordInst();
      temp_35 = (temp_34 + 1);
      int temp_36;
      recordInst();
      temp_36 = array_3[temp_35] ;
      recordInst();
      if ((temp_33 <= temp_36)) goto L35;
      {
      int temp_37;
      recordInst();
      temp_37 = (1 * idx);
      recordInst();
      temp = array_1[temp_37] ;
      int temp_38;
      recordInst();
      temp_38 = (1 * idx);
      int temp_39;
      recordInst();
      temp_39 = (1 * idx);
      int temp_40;
      recordInst();
      temp_40 = (temp_39 + 1);
      recordInst();
      array_3[temp_38]  = array_3[temp_40] ;
      int temp_41;
      recordInst();
      temp_41 = (1 * idx);
      int temp_42;
      recordInst();
      temp_42 = (temp_41 + 1);
      recordInst();
      array_3[temp_42]  = temp;
      recordInst();
      idx = 0;
      recordInst();
      goto L33;
      }
   L35:;
      recordInst();
      idx = (idx + 1);
      }
   L33:;
      int temp_43;
      recordInst();
      temp_43 = (bound - 1);
      recordInst();
      if ((idx < temp_43)) goto L32;
      recordInst();
      idx = 0;
      recordInst();
      goto L38;
   L37:;
      {
      int temp_44;
      recordInst();
      temp_44 = (1 * idx);
      int temp_45;
      recordInst();
      temp_45 = array_4[temp_44] ;
      int temp_46;
      recordInst();
      temp_46 = (1 * idx);
      int temp_47;
      recordInst();
      temp_47 = (temp_46 + 1);
      int temp_48;
      recordInst();
      temp_48 = array_4[temp_47] ;
      recordInst();
      if ((temp_45 <= temp_48)) goto L40;
      {
      int temp_49;
      recordInst();
      temp_49 = (1 * idx);
      recordInst();
      temp = array_4[temp_49] ;
      int temp_50;
      recordInst();
      temp_50 = (1 * idx);
      int temp_51;
      recordInst();
      temp_51 = (1 * idx);
      int temp_52;
      recordInst();
      temp_52 = (temp_51 + 1);
      recordInst();
      array_4[temp_50]  = array_4[temp_52] ;
      int temp_53;
      recordInst();
      temp_53 = (1 * idx);
      int temp_54;
      recordInst();
      temp_54 = (temp_53 + 1);
      recordInst();
      array_4[temp_54]  = temp;
      recordInst();
      idx = 0;
      recordInst();
      goto L38;
      }
   L40:;
      recordInst();
      idx = (idx + 1);
      }
   L38:;
      int temp_55;
      recordInst();
      temp_55 = (bound - 1);
      recordInst();
      if ((idx < temp_55)) goto L37;
      recordInst();
      print_arrays();
      }
      report();
      return 0;
   L21:;
}
/* FileAst "sort.adap" End */
/* ProgAst "sort.adap" End */
