#include <stdio.h>
int Counter;
RecordInst(){Counter++;}
Init(){Counter = 0;}
Report(){printf("No. of instructions are %d\n", Counter);}
/* FileAst "jacobi.adap" Begin */
int a[262144];
int b[262144];
int main() ;

int main() {
      int temp_38;
      int temp_39;
      int temp_35;
      int temp_36;
      int temp_37;
      int temp_32;
      int temp_33;
      int temp_34;
      int temp_11;
      int temp_28;
      int temp_29;
      int temp_30;
      int temp_31;
      int temp_12;
      int temp_24;
      int temp_25;
      int temp_26;
      int temp_27;
      int temp_13;
      int temp_19;
      int temp_20;
      int temp_21;
      int temp_23;
      int temp_22;
      int temp_14;
      int temp_15;
      int temp_16;
      int temp_18;
      int temp_17;
      int temp_8;
      int temp_9;
      int temp_10;
      int temp_7;
      int temp_4;
      int temp_5;
      int temp_6;
      int temp_3;
      int temp_0;
      int temp_1;
      int temp_2;
      int i;
      int j;
      Init();
      RecordInst();
      i = 0;
   L2:;
      RecordInst();
      j = 0;
   L6:;
      RecordInst();
      temp_2 = (512 * i);
      RecordInst();
      temp_1 = (j + temp_2);
      RecordInst();
      temp_0 = (1 * temp_1);
      RecordInst();
      temp_3 = (i + 12);
      RecordInst();
      a[temp_0]  = (temp_3 + j);
      RecordInst();
      temp_6 = (512 * i);
      RecordInst();
      temp_5 = (j + temp_6);
      RecordInst();
      temp_4 = (1 * temp_5);
      RecordInst();
      temp_7 = (i + 12);
      RecordInst();
      b[temp_4]  = (temp_7 + j);
   L7:;
      RecordInst();
      j = (j + 1);
      RecordInst();
      if ((j < 512)) goto L6;
   L3:;
      RecordInst();
      i = (i + 1);
      RecordInst();
      if ((i < 512)) goto L2;
      RecordInst();
      i = 0;
   L11:;
      RecordInst();
      j = 0;
   L15:;
      RecordInst();
      temp_10 = (512 * j);
      RecordInst();
      temp_9 = (i + temp_10);
      RecordInst();
      temp_8 = (1 * temp_9);
      RecordInst();
      temp_17 = (i - 1);
      RecordInst();
      temp_18 = (512 * j);
      RecordInst();
      temp_16 = (temp_17 + temp_18);
      RecordInst();
      temp_15 = (1 * temp_16);
      RecordInst();
      temp_14 = b[temp_15] ;
      RecordInst();
      temp_22 = (i + 1);
      RecordInst();
      temp_23 = (512 * j);
      RecordInst();
      temp_21 = (temp_22 + temp_23);
      RecordInst();
      temp_20 = (1 * temp_21);
      RecordInst();
      temp_19 = b[temp_20] ;
      RecordInst();
      temp_13 = (temp_14 + temp_19);
      RecordInst();
      temp_27 = (i + j);
      RecordInst();
      temp_26 = (1 * temp_27);
      RecordInst();
      temp_25 = (temp_26 - 512);
      RecordInst();
      temp_24 = b[temp_25] ;
      RecordInst();
      temp_12 = (temp_13 + temp_24);
      RecordInst();
      temp_31 = (i + j);
      RecordInst();
      temp_30 = (1 * temp_31);
      RecordInst();
      temp_29 = (temp_30 + 512);
      RecordInst();
      temp_28 = b[temp_29] ;
      RecordInst();
      temp_11 = (temp_12 + temp_28);
      RecordInst();
      a[temp_8]  = (0.25 * temp_11);
   L16:;
      RecordInst();
      j = (j + 1);
      RecordInst();
      if ((j < 511)) goto L15;
   L12:;
      RecordInst();
      i = (i + 1);
      RecordInst();
      if ((i < 511)) goto L11;
      RecordInst();
      i = 0;
   L20:;
      RecordInst();
      j = 0;
   L24:;
      RecordInst();
      temp_34 = (512 * j);
      RecordInst();
      temp_33 = (i + temp_34);
      RecordInst();
      temp_32 = (1 * temp_33);
      RecordInst();
      temp_37 = (512 * j);
      RecordInst();
      temp_36 = (i + temp_37);
      RecordInst();
      temp_35 = (1 * temp_36);
      RecordInst();
      b[temp_32]  = a[temp_35] ;
   L25:;
      RecordInst();
      j = (j + 1);
      RecordInst();
      if ((j < 511)) goto L24;
   L21:;
      RecordInst();
      i = (i + 1);
      RecordInst();
      if ((i < 511)) goto L20;
      RecordInst();
      temp_39 = (256 + 131072);
      RecordInst();
      temp_38 = b[temp_39] ;
      RecordInst();
      printf("The sampled element is %d\n", temp_38);
      Report();
      return 0;
   L1:;
      Report();
}
/* FileAst "jacobi.adap" End */

