#include <stdio.h>
int Counter;
RecordInst(){Counter++;}
Init(){Counter = 0;}
Report(){printf("No. of instructions are %d\n", Counter);}
/* FileAst "movingedge.adap" Begin */
int nbr_5[5];
int magic= 35 ;
int V[100];
void init_nbr() ;

void init_nbr() {
      RecordInst();
      nbr_5[0]  = - 3;
      RecordInst();
      nbr_5[1]  = 12;
      RecordInst();
      nbr_5[2]  = 17;
      RecordInst();
      nbr_5[3]  = 12;
      RecordInst();
      nbr_5[4]  = - 3;
   L1:;
}
int getinput() ;

int getinput() {
      int a;
      RecordInst();
      a = - 1;
      RecordInst();
      goto L4;
   L3:;
      RecordInst();
      scanf("%d", (&a));
      RecordInst();
      if ((0 > a)) goto L9;
      RecordInst();
      if ((a <= 100)) goto L7;
   L9:;
      RecordInst();
      printf("I need a non-negative number less than 100: ");
      RecordInst();
      a = - 1;
   L7:;
   L4:;
      RecordInst();
      if ((0 > a)) goto L3;
      return a;
   L2:;
}
void moving(int p0) ;

void moving(int size) {
      int temp;
      int temp_8;
      int temp_7;
      int temp_0;
      int temp_4;
      int temp_5;
      int temp_6;
      int temp_1;
      int temp_2;
      int temp_3;
      int i;
      int j;
      RecordInst();
      size = size;
      RecordInst();
      i = 2;
      RecordInst();
      goto L15;
   L12:;
      RecordInst();
      temp = 0;
      RecordInst();
      j = - 2;
   L16:;
      RecordInst();
      temp_3 = (i + j);
      RecordInst();
      temp_2 = (1 * temp_3);
      RecordInst();
      temp_1 = V[temp_2] ;
      RecordInst();
      temp_6 = (1 * j);
      RecordInst();
      temp_5 = (temp_6 + 2);
      RecordInst();
      temp_4 = nbr_5[temp_5] ;
      RecordInst();
      temp_0 = (temp_1 * temp_4);
      RecordInst();
      temp = (temp + temp_0);
   L17:;
      RecordInst();
      j = (j + 1);
      RecordInst();
      if ((j < 3)) goto L16;
      RecordInst();
      temp_7 = (1 * i);
      RecordInst();
      V[temp_7]  = (temp / magic);
   L13:;
      RecordInst();
      i = (i + 1);
   L15:;
      RecordInst();
      temp_8 = (size - 2);
      RecordInst();
      if ((i < temp_8)) goto L12;
   L11:;
}
int main() ;

int main() {
      int redat2;
      int temp_12;
      int temp_13;
      int temp_10;
      int temp_11;
      int temp_9;
      int redat1;
      int size;
      int i;
      Init();
      RecordInst();
      printf("Please input the size of the vector to be transformed: ");
      RecordInst();
      redat1 = getinput();
      RecordInst();
      size = redat1;
      RecordInst();
      i = 0;
      RecordInst();
      goto L25;
   L22:;
      RecordInst();
      redat2 = rand();
      RecordInst();
      temp_9 = (1 * i);
      RecordInst();
      V[temp_9]  = (redat2 % 100);
   L23:;
      RecordInst();
      i = (i + 1);
   L25:;
      RecordInst();
      if ((i < size)) goto L22;
      RecordInst();
      printf("Original vector:\n");
      RecordInst();
      i = 0;
      RecordInst();
      goto L30;
   L27:;
      RecordInst();
      temp_11 = (1 * i);
      RecordInst();
      temp_10 = V[temp_11] ;
      RecordInst();
      printf("%d\n", temp_10);
   L28:;
      RecordInst();
      i = (i + 1);
   L30:;
      RecordInst();
      if ((i < size)) goto L27;
      RecordInst();
      printf("\n");
      RecordInst();
      init_nbr();
      RecordInst();
      moving(size);
      RecordInst();
      printf("Moving edge vector:\n");
      RecordInst();
      i = 0;
      RecordInst();
      goto L37;
   L34:;
      RecordInst();
      temp_13 = (1 * i);
      RecordInst();
      temp_12 = V[temp_13] ;
      RecordInst();
      printf("%d\n", temp_12);
   L35:;
      RecordInst();
      i = (i + 1);
   L37:;
      RecordInst();
      if ((i < size)) goto L34;
      RecordInst();
      printf("\n");
      Report();
      return 0;
   L20:;
      Report();
}
/* FileAst "movingedge.adap" End */
