name: Project 1

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
    schedule:
      # Schedule to run at 00:00 UTC on the 1st of every month
      - cron: '0 0 1 * *'
jobs:
  build-and-run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make build
      run: |
        cd proj/proj1
        make clean
        make build
    - name: make compile
      run: |
        cd proj/proj1
        make clean
        make build
        make compile
    - name: make run
      run: |
        cd proj/proj1
        make clean
        make build
        make compile
        make run

